---
mesos_version: "1.6.0"

mesos_repo_host: repos.mesosphere.com

# Debian
mesos_package_version: "2.0.4"
mesos_os_distribution: "{{ ansible_distribution | lower }}"
mesos_os_version: "{{ ansible_distribution_version.split('.') | join('') }}"
mesos_package_full_version: "{{ mesos_version }}-{{ mesos_package_version }}.{{ mesos_os_distribution }}{{ mesos_os_version }}"
mesosphere_apt_url: "http://{{ mesos_repo_host }}/{{ ansible_distribution | lower }}"
mesos_apt_package: "mesos={{ mesos_package_full_version }}"


# conf file settings
mesos_cluster_name: "mesos_vakees_cluster"
mesos_ip: "{{ ansible_default_ipv4.address }}"
mesos_hostname: "{{ inventory_hostname }}"
mesos_master_port: "5050"
mesos_slave_port: "5051"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_work_dir: "/var/mesos"
mesos_quorum: "1"
zookeeper_client_port: "2181"
zookeeper_hostnames: "{{ groups['master']| join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port }}" #"{{ mesos_hostname }}:{{ zookeeper_client_port }}"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}/mesos"
mesos_owner: root
mesos_group: root

# Containerizer
mesos_containerizers: "docker,mesos"
mesos_executor_timeout: "5mins"

mesos_additional_configs: []
  # For example:
  # - name: FOO
  #   value: bar
